layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects: Resume
    # - repo-name

social_media:
  hackerrank: mhole44
  linkedin: michael-hole
  twitter: mhole44
  website: https://mhole44.github.io

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: ML
    web_url: https://github.com/topics/ml
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3xqTfdcuL1QYKCQkFzwX9ZAwHH7KaY0qrplXRwLJtmlqdrvHyUw

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed


title: Michael Hole
# Resume settings
resume_avatar:                  "true"
resume_name:                    "Michael Hole - UNDER DEV"
resume_title:                   "Student at UC Berkeley"

# used for the contact button in _layouts/index.html
resume_contact_email:           "mhole44@berkeley.edu"

# the next two items are used for schema itemprops in _layouts/index.html
resume_contact_telephone:       "(805) 478-0995"
resume_contact_address:         "Berkeley, CA"

resume_header_contact_info:     "Berkeley, CA • (805) 478-0995 • mhole44@berkeley.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mhole44"
  resume_twitter_url:           "http://twitter.com/mhole44"
  resume_linkedin_url:          "https://www.linkedin.com/in/michael-hole"
  resume_website_url:           "http://mhole44.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
